ALTER TABLE PERSONS 
ADD type VARCHAR2(100) DEFAULT 'person';

CREATE TABLE movie_actors (
  movie_id 
);

DROP TABLE "movie_actors";
DROP TABLE MOVIES;
DROP TABLE PERSONS;

DROP TABLE MOVIE_ACTORS;
COMMIT;


CREATE TABLE STUDENT.PERSONS (
  ID   NUMBER             NOT NULL,
  NAME VARCHAR2(20 BYTE)  NOT NULL,
  TYPE VARCHAR2(100 BYTE) DEFAULT 'person',
  CONSTRAINT PERSONS_PK PRIMARY KEY (ID) USING INDEX TABLESPACE USERS STORAGE (INITIAL 64 K
                                                                               MAXEXTENTS UNLIMITED)
)
TABLESPACE USERS
STORAGE (INITIAL 64 K
         MAXEXTENTS UNLIMITED)
LOGGING;

/
CREATE TABLE STUDENT.MOVIES (
  ID          NUMBER          NOT NULL,
  TITLE       VARCHAR2(20 BYTE) NOT NULL,
  DIRECTOR_ID NUMBER            NOT NULL,
  CONSTRAINT MOVIES_PK PRIMARY KEY (ID) USING INDEX TABLESPACE USERS STORAGE (INITIAL 64 K
                                                                              MAXEXTENTS UNLIMITED),
  CONSTRAINT FK_MOVIES_PERSONS FOREIGN KEY (DIRECTOR_ID)
  REFERENCES STUDENT.PERSONS (ID) ON DELETE CASCADE
)
TABLESPACE USERS
STORAGE (INITIAL 64 K
         MAXEXTENTS UNLIMITED)
LOGGING;
/
CREATE TABLE STUDENT.MOVIE_ACTORS (
  "movie_id" NUMBER(*, 0),
  "actor_id" NUMBER(*, 0),
  "id"       NUMBER(*, 0),
  CONSTRAINT FK_MOVIE_ACTORS_ACTOR_ID FOREIGN KEY ("actor_id")
  REFERENCES STUDENT.PERSONS (ID),
  CONSTRAINT FK_MOVIE_ACTORS_MOVIE_ID FOREIGN KEY ("movie_id")
  REFERENCES STUDENT.MOVIES (ID),
  CONSTRAINT PK_MOVIE_ACTORS_ID PRIMARY KEY ("id")
)
TABLESPACE USERS
LOGGING;

COMMIT;

CREATE SEQUENCE person_sq
 START WITH     1
 INCREMENT BY   1;

CREATE SEQUENCE movie_sq
 START WITH     1
 INCREMENT BY   1;


COMMIT;

INSERT INTO PERSONS (name, TYPE) VALUES ('ionica', 'actor');



INSERT INTO PERSONS (id, NAME, type) VALUES (1, 'ion', 'person');

INSERT INTO Movies (id, title, director_id) VALUES (1, 'GOT', 1);

INSERT INTO MOVIE_ACTORS (Id, MOVIE_ID, ACTOR_ID) VALUES (1, 1, 1);

INSERT INTO MOVIE_ACTORS











